In [1]:
import numpy as np
import math

Array Creation

In [2]:
array1 = np.array([1, 2, 3])
print(array1)
type(array1)

[1 2 3]


numpy.ndarray

In [3]:
print(array1.ndim)

1


In [4]:
one_dimentional_array = np.array([1, 2, 3])
print(one_dimentional_array)
print(one_dimentional_array.ndim)

[1 2 3]
1


In [5]:
two_dimentional_array = np.array([[1, 2, 3], [4, 5, 6]])
print(two_dimentional_array)
print(two_dimentional_array.ndim)

[[1 2 3]
 [4 5 6]]
2


In [6]:
three_dimentional_array = np.array([[[1, 2, 3], [4, 5, 6]]])
print(three_dimentional_array)
print(three_dimentional_array.ndim)

[[[1 2 3]
  [4 5 6]]]
3


Shape

In [7]:
print(one_dimentional_array.shape)
print(two_dimentional_array.shape)   #classical once (2, 3)
print(three_dimentional_array.shape)

(3,)
(2, 3)
(1, 2, 3)


data type

In [8]:
print(one_dimentional_array.dtype)
print(two_dimentional_array.dtype)   #classical once 
print(three_dimentional_array.dtype)

int32
int32
int32


zero,one

In [9]:
zeros_array = np.zeros((2, 3))
print(zeros_array)
ones_array = np.ones((2, 3))
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


eye

In [10]:
eye_arry = np.eye(5)    # identity matrix --> 5*5 array of 0 with 1 diagonal 
print(eye_arry)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
selected_array = np.linspace(0, 10, 3)    # array of 3 values between 0, less than 10
print(selected_array)

[ 0.  5. 10.]


In [12]:
arrangment_array = np.arange(0, 10, 2)   # array from 0, to less than 10 with step of 2
print(arrangment_array)

[0 2 4 6 8]


In [13]:
full_array = np.full((2, 3), 5)     # 2*3 array with all values of 5
print(full_array)

[[5 5 5]
 [5 5 5]]


In [14]:
random_arr = np.random.rand(2, 3)   # 2*3 array of random floats values between 0-1
print(random_arr)

[[0.87651219 0.77530094 0.14504494]
 [0.62262206 0.17235363 0.32016477]]


In [15]:
random_array = np.random.randint(5, size=(2, 3))  # 2*3 array with roandom ints between 0-4
print(random_array)

[[0 2 2]
 [2 4 2]]


Inspecting properties

In [16]:
my_array = np.array([[10, 20, 30], [5, 10, 15]])
print(my_array)
print(my_array.size)   # no. of elements 
print(my_array.shape)
print(my_array.dtype)
#print(my_array.info)

my_list = my_array.tolist()   # convert array to list
print(my_list)
type(my_list)

[[10 20 30]
 [ 5 10 15]]
6
(2, 3)
int32
[[10, 20, 30], [5, 10, 15]]


list

Array Operations

In [17]:
a = np.array([10,20,30,40])
b = np.array([1, 2, 3,4])

c = a + b 
print(c)

[11 22 33 44]


In [18]:
d = a*b
print(d)

[ 10  40  90 160]


In [19]:
# Besides elementwise manipulation, it is important to know that numpy supports matrix manipulation. Let's
# look at matrix product. if we want to do elementwise product, we use the "*" sign
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

print(A.shape)
print(B.shape)

print(A*B)

(2, 2)
(2, 2)
[[2 0]
 [0 4]]


In [20]:
# if we want to do matrix product, we use the "@" sign or use the dot function
print(A@B)

[[5 4]
 [3 4]]


In [21]:
array1 = np.array([1, 1, 2])
array2 = np.array([0, 2, 3])

array3 = array1+array2

print(array3)
print(array3.dtype)
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

[1 3 5]
int32
9
5
1
3.0


adding / removing elements

In [22]:
array_4 = np.array([1, 2, 3])

array_5 = np.append(array_4, 5)  # add only 1 element at a time to the end of the array
print(array_5)

[1 2 3 5]


In [23]:
array_6 = np.insert(array_4, 2, 10)  # insert in array_4 , the value(10) before index 2
print(array_6)

[ 1  2 10  3]


In [24]:
array_7 = np.insert(array_4, 2, [10, 12])  # insert values 10 and 12 before index 2
print(array_7)

[ 1  2 10 12  3]


In [25]:
array_8 = np.delete(array_4, 1, axis=0)  # delete index 1
array_8

array([1, 3])